### ISSUE TITLE
assoc Command and Question

### ISSUE THREAD

**Issue by NewthanGuy** [NewthanGuy/CMDV5#2]
Sooo Originally assoc wasnt in CmdV3 And CmdV4 but i added It for Fun Windfuf i call that a New update

And windfuf should i make a Walp.bmp Wallpaper Pack

For CmdV4/CMDV5

**Comment by Zinffo** [comment]
yeah you should

**Comment by Zinffo** [comment]
also i added an section for additional commands in the bottom of the batch file in CMDV5

**Comment by MichaelEpicA** [comment]
dude what the fuck is this

**Comment by MichaelEpicA** [comment]
the best idea when i get an email about this being closed
